### ISSUE TITLE
plugin should not check test classes by default

### ISSUE THREAD

**Issue by jtnord** [mojohaus/animal-sniffer#142]
#80 introduced the ability to check test classes, however it defaulted this to on.

this is a change in behaviour - and for the most part I would argue that using newer APIs in test code that does not get delivered as part of the product is completely acceptable.  (there are situations where you do push a `test-jar` that you may want this check enabled for - but this would not be the normal)

therefore the brhaviour should default to off so that configuration by convention wins for the majority of the projects

**Comment by famod** [comment]
The main idea was to have it consistent, especially for cases where developer A is working on a project with JDK 8 and another developer B is working with JDK 11, which is not that rare for smaller open source projects.
So this aspect is not about shipping/delivering.

I hope there will be a clear note in the changelog, otherwise people might not realize they now have to enable the property. /cc @olamy
